import type { AgencyConfig, AgentDefinition } from './types.js';

/** Filesystem-safe kebab-case slug from an agent name. */
export function agentSlug(name: string): string {
  return name
    .trim()
    .replace(/[_\s]+/g, '-')
    .replace(/[^a-zA-Z0-9-]/g, '')
    .toLowerCase();
}

function nodeId(name: string): string {
  // mermaid identifiers must not contain spaces or punctuation
  return name.replace(/[^a-zA-Z0-9_]/g, '_');
}

function nodeLabel(agent: AgentDefinition): string {
  const lines = [`<b>${agent.name}</b>`];
  if (agent.position) lines.push(`<i>${agent.position}</i>`);
  if (agent.tools?.length) {
    lines.push('---');
    lines.push(agent.tools.map((t) => `🔧 ${t}`).join('<br/>'));
  }
  return lines.join('<br/>');
}

/**
 * Render a mermaid `flowchart TD` for the given agency.
 * - Solid arrows: orchestrator → each worker (delegation, supervisor strategy)
 * - Dashed arrows: collaboration edges from `collaboratesWith`
 */
export function renderOrgChart(config: AgencyConfig): string {
  const lines: string[] = [];
  lines.push('%% Auto-generated by `animaos create`');
  lines.push(`%% Agency: ${config.name}`);
  if (config.mission) lines.push(`%% Mission: ${config.mission}`);
  lines.push('');
  lines.push('flowchart TD');

  const orch = config.orchestrator;
  const orchId = nodeId(orch.name);
  lines.push(`  ${orchId}["${nodeLabel(orch)}"]:::orchestrator`);

  for (const agent of config.agents) {
    const id = nodeId(agent.name);
    lines.push(`  ${id}["${nodeLabel(agent)}"]:::worker`);
  }

  // Delegation edges (solid)
  for (const agent of config.agents) {
    lines.push(`  ${orchId} --> ${nodeId(agent.name)}`);
  }

  // Collaboration edges (dashed) — dedupe by sorting the pair
  const drawnPairs = new Set<string>();
  const drawCollab = (from: AgentDefinition) => {
    for (const peer of from.collaboratesWith ?? []) {
      const pair = [from.name, peer].sort().join('::');
      if (drawnPairs.has(pair)) continue;
      drawnPairs.add(pair);
      lines.push(`  ${nodeId(from.name)} -.->|collab| ${nodeId(peer)}`);
    }
  };
  drawCollab(orch);
  for (const agent of config.agents) drawCollab(agent);

  lines.push('');
  lines.push('  classDef orchestrator fill:#fef3c7,stroke:#b45309,stroke-width:2px;');
  lines.push('  classDef worker fill:#dbeafe,stroke:#1e40af,stroke-width:1px;');

  return lines.join('\n');
}

/**
 * Render the agency as a markdown brief — mission, values, and the diagram —
 * suitable to drop into a README or docs site.
 */
export function renderAgencyBrief(config: AgencyConfig): string {
  const out: string[] = [];
  out.push(`# ${config.name}`);
  out.push('');
  out.push(`> ${config.description}`);
  out.push('');

  if (config.mission) {
    out.push('## Mission');
    out.push('');
    out.push(config.mission);
    out.push('');
  }

  if (config.values?.length) {
    out.push('## Values');
    out.push('');
    for (const v of config.values) out.push(`- ${v}`);
    out.push('');
  }

  out.push('## Org chart');
  out.push('');
  out.push('```mermaid');
  out.push(renderOrgChart(config));
  out.push('```');
  out.push('');

  out.push('## Roster');
  out.push('');
  const renderAgent = (a: AgentDefinition, marker: string) => {
    const title = a.position ? `${a.name} — ${a.position}` : a.name;
    out.push(`### ${marker} ${title}`);
    out.push('');
    out.push(a.bio);
    if (a.tools?.length) {
      out.push('');
      out.push(`**Skills:** ${a.tools.join(', ')}`);
    }
    if (a.collaboratesWith?.length) {
      out.push(`**Collaborates with:** ${a.collaboratesWith.join(', ')}`);
    }
    out.push('');
  };
  renderAgent(config.orchestrator, '★');
  for (const a of config.agents) renderAgent(a, '•');

  return out.join('\n');
}

/**
 * Personnel-file-style profile for a single agent.
 * Lives in `agents/<slug>/profile.md` — a human-readable record of who this agent is.
 */
export function renderAgentProfile(
  agent: AgentDefinition,
  agencyName: string
): string {
  const out: string[] = [];
  const headline = agent.position ? `${agent.name} — ${agent.position}` : agent.name;
  out.push(`# ${headline}`);
  out.push('');
  out.push(`*${agencyName}${agent.role === 'orchestrator' ? ' · orchestrator' : ''}*`);
  out.push('');

  out.push('## Bio');
  out.push('');
  out.push(agent.bio);
  out.push('');

  if (agent.lore) {
    out.push('## Backstory');
    out.push('');
    out.push(agent.lore);
    out.push('');
  }

  if (agent.adjectives?.length) {
    out.push(`**Personality:** ${agent.adjectives.join(', ')}`);
    out.push('');
  }

  if (agent.style) {
    out.push(`**Communication style:** ${agent.style}`);
    out.push('');
  }

  if (agent.topics?.length) {
    out.push('## Expertise');
    out.push('');
    for (const t of agent.topics) out.push(`- ${t}`);
    out.push('');
  }

  if (agent.knowledge?.length) {
    out.push('## Knows deeply');
    out.push('');
    for (const k of agent.knowledge) out.push(`- ${k}`);
    out.push('');
  }

  if (agent.tools?.length) {
    out.push('## Skills');
    out.push('');
    for (const t of agent.tools) out.push(`- 🔧 \`${t}\``);
    out.push('');
  }

  if (agent.collaboratesWith?.length) {
    out.push('## Frequent collaborators');
    out.push('');
    for (const c of agent.collaboratesWith) out.push(`- ${c}`);
    out.push('');
  }

  out.push('## Mandate');
  out.push('');
  out.push(agent.system);
  out.push('');

  out.push('---');
  out.push('');
  out.push('## Workspace');
  out.push('');
  out.push('- `assets/` — avatars, images, brand kit (drop files here)');
  out.push('- `memory/` — agent-specific memory and notes');
  out.push('- `memory/seed.json` — optional pre-loaded memories, posted to the daemon on every launch');

  return out.join('\n');
}
